### PR TITLE
Add `+all` variants to JetBrains templates to ignore the whole .idea …

### PR DESCRIPTION
**Pull request by orzechow**
…folder

Also adds corresponding aliases:

- AppCode
- CLion
- Intellij
- PhpStorm
- PyCharm
- RubyMine
- WebStorm

### CODE REVIEW

**Comment by adamvoss** [comment]
If this is "all", should it also ignore ***.iml** files?

**Comment by joeblau** [comment]
That's a good idea.  There also needs to be a rewrite of part of this stuff because we're not reliant on GitHub anymore.  A lot of these patches can just go away.

**Comment by jessemillar** [comment]
@joeblau Any ETA on that rewrite? At least for IntelliJ Idea?

**Comment by joeblau** [comment]
I don't have an ETA.  I'm primarily an iOS developer so it's not a big pain point for me just yet.  However, I'm learning Android so I might have start updating the template soon.

**Pull request merged**
