### PR TITLE
Add the 'bin' dir to Python gitignore

### PR DESCRIPTION
**Pull request by GeekMasher**
# Pull Request

Thank you for contributing to @dvcs/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

When using `virtualenv`, the tool creates a `./bin/` folder containing the `activate`, `python`, `pip`, etc. scripts/binaries. These shouldn't be included into the projects source code.

### CODE REVIEW

**Comment by joeblau** [comment]
This is already included in the `VirtualEnv` stack but the file is named incorrectly.  I'll fix the file name and this should be fixed.

https://github.com/dvcs/gitignore/blob/master/templates/VirtualEnv.gitignore

**Comment by GeekMasher** [comment]
Ah excellent. So if I create a Python project and use `virtualenv`, I should use `Python` + `VirtualEnv`?

**Comment by joeblau** [comment]
https://www.gitignore.io/api/python adds the VirtualEnv template.

**Comment by GeekMasher** [comment]
This has only been recently added as I have a copy of the old gitignore file using this exact API and it doesn't have the VirtualEnv stuff in.
Thanks for fixing this.

**Comment by joeblau** [comment]
Thanks for helping me find the big!

**Pull request closed without merging**
