### PR TITLE
for Vanilla nativescript

### PR DESCRIPTION
**Pull request by zenz**
Avoid js file lost for vanilla nativescript programming.

# Pull Request

Thank you for contributing to @dvcs/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [ ] Template - Update existing `.gitignore` template

## Details

*replace this section with links and/or info about the proposed request*

### CODE REVIEW

**Comment by joeblau** [comment]
Can you just delete the line if it's not necessary?

**Comment by zenz** [comment]
@joeblau as a basic function, it should keep basic things done, in my opinion, if you want to remove some files, you should add a line to do it.

**Comment by joeblau** [comment]
ah okay, then could you split the comment and the line into separate lines.

```
# shouldn't ignore this for vanilla nativescript 
# /app/**/*.js
```

that way someone can uncomment the JS line and still keep the comment?

**Comment by zenz** [comment]
@joeblau you are right, I modified it.

**Comment by joeblau** [comment]
👍

**Pull request merged**
