### PR TITLE
[add] created by pipenv

### PR DESCRIPTION
**Pull request by dohq**
### Update

- [x] Template - Update existing `.gitignore` template

## Details

Use pipenv and enable `PIPENV_VENV_IN_PROJECT` option.
The dir name is fixed.
e.g 
https://github.com/pypa/pipenv/blob/master/docs/advanced.rst#-configuration-with-environment-variables

### CODE REVIEW

**Comment by joeblau** [comment]
Due to change #116 this fails the build because it's checking your change against GitHub's master list.  Can you create a `Python.patch` file and add this line to that file.  That will allow the build to pass.

**Comment by dohq** [comment]
OK!
Plese wait a minute until the corresponding.

**Comment by joeblau** [comment]
github.com/github/gitignore is the main list of these templates and the build system checks to make sure that all of our local templates are kept up to date with the changes in that repo.  What that means is that if you want to change one of the templates that is maintained by GitHub without waiting for them to accept your pull request, you need to create a `.patch` file.  This patch file will apply any additional changes you want.

All you have to do is.
1. Make a new file called `Python.patch`
2. Remove the line you made in `Python.gitignore` and add it to `Python.patch`
3. Re-submit this pull request

The build will be green and I'll merge it as soon as I see it.

**Comment by dohq** [comment]
Thank you for the advice.
I fiexd now.
Can you check this out?

**Comment by dohq** [comment]
Hmm...
`Python.patch`  contents
`.venv/` only oneline?

I'm sorry to be so inquisitive.

**Comment by dohq** [comment]
I see
I am sorry for taking your time.
I hope this in successful!

**Comment by joeblau** [comment]
No problem.  This setup is probably more complicated than it needs to be :)

**Pull request merged**
