### PR TITLE
Update Rust: documentation link

### PR DESCRIPTION
**Pull request by bchatard**
# Pull Request

Thank you for contributing to @dvcs/gitignore and https://www.gitignore.io.

## New or update

Select the appropriate check box for this pull request. This helps when merging to ensure there are no conflicts with other templates or misunderstandings of how thee template list works.

### New

- [ ] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

### Update

- [x] Template - Update existing `.gitignore` template

## Details

Update documentation link (already done in https://github.com/github/gitignore/blob/master/Rust.gitignore)

### CODE REVIEW

**Comment by bchatard** [comment]
@joeblau the result is not good on https://www.gitignore.io/api/rust 

Did I broke something?

**Comment by joeblau** [comment]
Ah, you're pull request already exists in the `rust.template`

https://github.com/dvcs/gitignore/blob/master/templates/Rust.template
https://github.com/dvcs/gitignore/blob/master/templates/Rust.patch

**Comment by bchatard** [comment]
sorry :-( 

I will make a new PR for updating the documentation link directly on `Rust.gitignore` file

**Comment by joeblau** [comment]
I already reverted the change in #95

**Pull request merged**
