### PR TITLE
Adding .gitignore for CocoaPods

### PR DESCRIPTION
**Pull request by ladland**
Annotated with instructions and tips from the CocoaPods Maintainers

### CODE REVIEW

**Comment by joeblau** [comment]
These are incorporated into [Swift](https://github.com/dvcs/gitignore/blob/master/templates/Swift.gitignore) and [Objective-C](https://github.com/dvcs/gitignore/blob/master/templates/Objective-C.gitignore).  We could refactor those templates to be stacks and make those two templates use this Cocoapods.

Also .DSStore is already in the [MacOS](https://github.com/dvcs/gitignore/blob/master/templates/macOS.gitignore) template.

**Comment by ladland** [comment]
I have refactored and patched the Objective-C.gitignore and Swift.gitignore files.

The macOS stuff has been removed

**Comment by joeblau** [comment]
Everything looks good, just one small thing (which I think i my fault for not explaining well.  You want to use a `.stack` not a `.patch` and the way you add patches is

<Ignore Template>.<PatchTemplate>.patch `symlinked` `PatchTemplate`.gitignore

So for Swift and Obj-c you would have

```sh
ln -s CocoaPods.gitignore Swift.CocoaPods.stack
ln -s CocoaPods.gitignore Objective-C.CocoaPods.stack
```

Then you can remove `Objective-C.patch` and `Swift.patch` files.

**Comment by ladland** [comment]
Done

**Pull request merged**
