### PR TITLE
Add Zig programming language template

### PR DESCRIPTION
**Pull request by fibric**
# Pull Request

Thank you for contributing to @dvcs/gitignore and https://www.gitignore.io.

### New

- [x] Template - New `.gitignore` template
- [ ] Composition - Template made from smaller templates
- [ ] Inheritance - Template similar to an existing template
- [ ] Patch - Template extending functionality of existing template

## Details

https://ziglang.org/

### CODE REVIEW

**Comment by fibric** [comment]
I don't understand the build system. The following files have differences (`git diff`):
- `Android.gitignore`
- `CMake.gitignore`
- `CodeSniffer.gitignore`
- `Python.gitignore`
- `Qt.gitignore`
- `Ruby.gitignore`
- `Unity.gitignore`

Haven't changed those files with my PR and they weren't touched in the previous commit.

**Comment by joeblau** [comment]
There Is a check that verifies that templates from the @github/gitingore repo are updated and it's not automated yet.

**Comment by fibric** [comment]
Thanks!

The `.moban.yaml` seems incomplete.
I count 485 `.gitignore` files in the `template/` folder but I find only 216 copy `.gitignore` entries in the `.moban.yaml` file.

**Comment by joeblau** [comment]
moan only compares the templates that would be required from @github/gitignore This repo  has way more templates than that one does.

**Pull request merged**
